### ISSUE TITLE
Slackでcommlogに投稿できるようにする

### ISSUE THREAD

**Issue by makenowjust** [makenowjust/commlog#51]
### TODO

- [ ] Slackに書き込んだ内容に、何らかのリアクションを付けたらcommlogに投稿されるようにする。

**Comment by MakeNowJust** [comment]
GitHubのGit Data APIでコミットを作成する - GeekFactory https://int128.hatenablog.com/entry/2017/09/05/161641

**Comment by MakeNowJust** [comment]
冷静に考えるとSlackのメッセージにcommlogしたい内容を丸々書くのは現実的じゃない気がする。

URLと一言書くといい感じにやってくれる、みたいなのがいいのかも。
